# NOTE: This docker container is built automatically
#       by the Docker Compose in the enclosing folder

FROM python:alpine

ADD . /code
WORKDIR /code

RUN pip3 install --requirement requirements.txt

# Make http port available to the world outside this container
EXPOSE 8000

# Define environment variables
# (none defined here -- define them in the docker run command)
# NOTE: The following environment variables can be set:
#	QUEUE_PREFIX dev- (optional -- defaults to empty string)
#	DEBUG_MODE True (optional -- defaults to False)
#   REDIS_URL (optional -- defaults to 'redis')
#   GRAPHITE_URL (optional -- defaults to 'localhost')

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "enqueueMain:app"]
